version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: hdeuser
      POSTGRES_PASSWORD: hdepassword
      POSTGRES_DB: hdedb
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
      